a = input("Enter number 1: ")
b = input("Enter number 2: ")
add = int(a)+int(b)
print("Addition: ", add)
sub = int(a)-int(b)
print("Subtraction: ", sub)
mul = int(a)*int(b)
print("Multiplication: ", mul)
div = int(a)/int(b)
print("Division: ", div)
mod = int(a) % int(b)
print("Remainder: ", mod)
exp = int(a)**int(b)
print("Exponent: ", exp)